import hashlib
import os
import random
from datetime import datetime

import numpy as np
import torch


EXPERIMENT_NAME_MAX_BYTES = 255


def limit_experiment_name_component(
    name: str, max_bytes: int = EXPERIMENT_NAME_MAX_BYTES
) -> str:
    """Fit an experiment directory name within a filesystem component limit.

    Linux filesystems commonly cap a single path component at 255 bytes. Keep
    valid names unchanged; for an overlong name, retain a readable prefix and
    append a deterministic digest so distinct configurations cannot collapse
    onto the same directory after shortening.
    """

    encoded = str(name).encode("utf-8")
    if len(encoded) <= max_bytes:
        return str(name)

    digest_suffix = f"_h{hashlib.sha256(encoded).hexdigest()[:12]}"
    suffix_bytes = len(digest_suffix.encode("ascii"))
    if max_bytes <= suffix_bytes:
        raise ValueError(
            "Experiment-name byte limit is too small for the collision-safe suffix."
        )

    prefix = encoded[: max_bytes - suffix_bytes].decode("utf-8", errors="ignore")
    prefix = prefix.rstrip(" ._-")
    shortened = f"{prefix}{digest_suffix}"
    if len(shortened.encode("utf-8")) > max_bytes:
        raise RuntimeError("Failed to enforce the experiment-name byte limit.")
    return shortened


class Config:
    # ==========================================
    # 1. Path configurations
    # ==========================================
    # Keep local outputs under the project checkout by default. Public users can
    # override project, dataset, and experiment locations with environment vars.
    BASE_DIR = os.path.abspath(
        os.environ.get("RP_PROJECT_ROOT", os.path.dirname(__file__))
    )
    DATASET_ROOT = os.path.abspath(
        os.environ.get("RP_DATASET_ROOT", os.path.join(BASE_DIR, "data"))
    )
    UNIFIED_DATA_DIR = os.path.join(DATASET_ROOT, "Unified_Dataset")
    SPLIT_DIR = os.path.join(UNIFIED_DATA_DIR, "splits")
    EXP_DIR = os.path.abspath(
        os.environ.get("RP_EXP_DIR", os.path.join(BASE_DIR, "Experiments"))
    )

    # ==========================================
    # 2. Experiment mode
    # ==========================================
    # Options:
    #   "B1_TCIA_TBX_BASELINE"
    #       Main baseline: TCIA TBx-confirmed radiologist target lesion ROIs only.
    #
    #   "B2_TCIA_SBX_ONLY"
    #       TCIA systematic-biopsy region supervision only.
    #
    #   "B3_TCIA_TBX_SBX"
    #       TCIA TBx-confirmed target ROIs + TCIA SBx region supervision.
    #
    #   Mixed-supervision source combinations:
    #       N1_RADIOLOGIST_ONLY   = RA only
    #       N2_PUB_TCIA_TBX_ONLY = RA + TBx
    #       N3_PUB_TCIA_SBX_ONLY = RA + SBx
    #       N4_MIXED              = RA + TBx + SBx
    #
    # Every experiment uses the same unmasked dense-RA + TCIA internal
    # evaluation cohorts and the same PROMIS external cohort. This allows all
    # supervision combinations to report metrics on identical patient sets:
    #   - lesion Dice on valid dense radiologist-mask cases;
    #   - patient-level risk-map metrics from available segmentation masks;
    #   - region-level risk-map metrics from available masks and zone maps.
    #
    # Training scripts may still select the mode in-process. Evaluation runners
    # set RP_EXPERIMENT_MODE before importing this module so each checkpoint is
    # reconstructed with the matching task/loss configuration.
    EXPERIMENT_MODE = os.environ.get(
        "RP_EXPERIMENT_MODE", "B1_TCIA_TBX_BASELINE"
    )

    # Shared evaluation cohorts generated by
    # preprocessing/Dataset_split_generator.py.
    COMMON_INTERNAL_VAL_CSV = os.path.join(
        SPLIT_DIR, "common_internal_evaluation.csv"
    )
    COMMON_INTERNAL_TEST_CSV = os.path.join(
        SPLIT_DIR, "common_internal_test.csv"
    )
    # This existing mixed-supervision split is the canonical PROMIS cohort.
    # All task wrappers point to this exact file rather than task-specific copies.
    COMMON_EXTERNAL_TEST_CSV = os.path.join(
        SPLIT_DIR, "N4_mixed_PROMIS_external_val.csv"
    )
    COMMON_FINAL_TEST_DATASETS = (
        ("internal", COMMON_INTERNAL_TEST_CSV),
        ("external", COMMON_EXTERNAL_TEST_CSV),
    )

    # Common checkpoints use the same patient-diagnosis endpoint across every
    # model. Native checkpoints instead follow each supervision task.
    COMMON_BEST_MODEL_METRIC = "patient_auprc"

    if EXPERIMENT_MODE == "B0_PATIENT_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B3_TCIA_TBx_SBx_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "patient_auprc"
        EXPERIMENT_TAG = "B0_StrictAbl_TCIA_PatientOnly"

    elif EXPERIMENT_MODE == "B1_TCIA_TBX_BASELINE":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B1_TCIA_TBx_baseline_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "tbx_native"
        EXPERIMENT_TAG = "B1_StrictAbl_TCIA_TBxROI"

    elif EXPERIMENT_MODE == "B2_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B2_TCIA_SBx_only_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "region_auprc"
        EXPERIMENT_TAG = "B2_StrictAbl_TCIA_SBxOnly"

    elif EXPERIMENT_MODE == "B3_TCIA_TBX_SBX":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B3_TCIA_TBx_SBx_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "tbx_sbx_native"
        EXPERIMENT_TAG = "B3_StrictAbl_TCIA_TBxROI_SBx"

    elif EXPERIMENT_MODE == "B4_TCIA_TBX_SBX_PATIENT":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "B3_TCIA_TBx_SBx_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = False
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 0.0
        LESION_SPARSE_LOSS_WEIGHT = 1.0
        LESION_SYS_LOSS_WEIGHT = 1.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "tbx_sbx_patient_native"
        EXPERIMENT_TAG = "B4_StrictAbl_TCIA_TBxROI_SBx_Patient"

    elif EXPERIMENT_MODE == "N1_RADIOLOGIST_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N1_radiologist_only_train.csv"
        )
        # Train strictly on cases with dense radiologist lesion masks.
        # Keep common validation unfiltered across dense-RA/TCIA cases
        # so the run can still report comparison metrics.
        TASK = "mixed"
        DATASET_TASK = "mixed"
        TRAIN_DATASET_TASK = "radiologist_only"
        VAL_DATASET_TASK = "mixed"
        TEST_DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = False

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "lesion_dice"
        EXPERIMENT_TAG = "N1_StrictAbl_PUBDenseOnly_CommonEval"

    elif EXPERIMENT_MODE == "N2_PUB_TCIA_TBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N2_PUB_TCIA_TBx_only_train.csv"
        )
        # The N2 training CSV contains dense radiologist + TCIA TBx supervision.
        # TCIA SBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = False
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.05
        LESION_SYS_LOSS_WEIGHT = 0.0

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 15
        LESION_SYS_START_EPOCH = 1

        BEST_MODEL_METRIC = "lesion_dice"
        EXPERIMENT_TAG = "N2_StrictAbl_RA_TBx_W005_Curr15_CommonEval"

    elif EXPERIMENT_MODE == "N3_PUB_TCIA_SBX_ONLY":
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N3_PUB_TCIA_SBx_only_train.csv"
        )
        # The N3 training CSV contains dense radiologist + TCIA SBx supervision.
        # TCIA TBx availability is hidden only in the training CSV.
        # The shared validation CSV keeps the original TBx and SBx labels.
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = False
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.0
        LESION_SYS_LOSS_WEIGHT = 0.25

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        # Match the N4 weak-supervision schedule: dense RA first, then SBx.
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 1
        LESION_SYS_START_EPOCH = 15

        BEST_MODEL_METRIC = "lesion_dice"
        EXPERIMENT_TAG = "N3_StrictAbl_RA_SBx_W025_Curr15_CommonEval"

    elif EXPERIMENT_MODE in {"N4_MIXED", "N4_MIXED_CLEAN", "N5_MIXED_PATIENT"}:
        TRAIN_CSV = os.path.join(
            SPLIT_DIR, "N4_mixed_PUB_TCIA_train.csv"
        )
        TASK = "mixed"
        DATASET_TASK = "mixed"

        USE_GRADE_TBX_TASK = False
        USE_GRADE_SBX_TASK = False
        USE_LESION_DENSE_TASK = True
        USE_LESION_SPARSE_TASK = True
        USE_LESION_SYS_TASK = True
        USE_GLAND_TASK = False

        LESION_DENSE_LOSS_WEIGHT = 1.0
        LESION_SPARSE_LOSS_WEIGHT = 0.05
        LESION_SYS_LOSS_WEIGHT = 0.25

        USE_EM_WEIGHTING = False
        USE_CURRICULUM = True

        # Evidence-guided N4 default after N2/N3 sweeps:
        # Epoch 1-14:  dense radiologist annotations only
        # Epoch 15+:   dense radiologist annotations + TCIA TBx + TCIA SBx
        LESION_DENSE_START_EPOCH = 1
        LESION_SPARSE_START_EPOCH = 15
        LESION_SYS_START_EPOCH = 15

        BEST_MODEL_METRIC = "lesion_dice"
        EXPERIMENT_TAG = (
            "N5_StrictAbl_W005_025_P005_Curr15_15_CommonEval"
            if EXPERIMENT_MODE == "N5_MIXED_PATIENT"
            else "N4_StrictAbl_W005_025_Curr15_15_CommonEval"
        )

    else:
        raise ValueError(
            "Unsupported EXPERIMENT_MODE: "
            f"{EXPERIMENT_MODE}. "
            "Use B0_PATIENT_ONLY, B1_TCIA_TBX_BASELINE, B2_TCIA_SBX_ONLY, "
            "B3_TCIA_TBX_SBX, B4_TCIA_TBX_SBX_PATIENT, or the "
            "N1/N2/N3/N4/N5 supervision combinations."
        )

    # Task-native selector. The common selector remains patient AUPRC.
    NATIVE_BEST_MODEL_METRIC_BY_MODE = {
        "B0_PATIENT_ONLY": "patient_auprc",
        "B1_TCIA_TBX_BASELINE": "tbx_native",
        "B2_TCIA_SBX_ONLY": "region_auprc",
        "B3_TCIA_TBX_SBX": "tbx_sbx_native",
        "B4_TCIA_TBX_SBX_PATIENT": "tbx_sbx_patient_native",
        "N1_RADIOLOGIST_ONLY": "lesion_dice",
        "N2_PUB_TCIA_TBX_ONLY": "lesion_dice",
        "N3_PUB_TCIA_SBX_ONLY": "lesion_dice",
        "N4_MIXED": "lesion_dice",
        "N4_MIXED_CLEAN": "lesion_dice",
        "N5_MIXED_PATIENT": "lesion_dice",
    }
    NATIVE_BEST_MODEL_METRIC = NATIVE_BEST_MODEL_METRIC_BY_MODE[EXPERIMENT_MODE]
    BEST_MODEL_METRIC = NATIVE_BEST_MODEL_METRIC

    # Universal evaluation protocol. Training supervision changes by experiment,
    # but validation and final-test patient sets never do.
    VAL_CSV = COMMON_INTERNAL_VAL_CSV
    INTERNAL_TEST_CSV = COMMON_INTERNAL_TEST_CSV
    TEST_CSV = COMMON_EXTERNAL_TEST_CSV
    FINAL_TEST_DATASETS = COMMON_FINAL_TEST_DATASETS

    # ==========================================
    # 3. Data and preprocessing
    # ==========================================
    TARGET_SPACING = [1.0, 1.0, 2.24]
    CROP_SIZE_SITK = [64, 64, 32]
    INPUT_SHAPE = (3, 32, 64, 64)
    # TCIA TBx supervision uses radiologist target lesion ROIs labelled by
    # target-biopsy-confirmed grade, not the inserted needle track.
    TCIA_TARGET_MASK_FILENAME = "target_mask.nii.gz"
    # Used only during preprocessing to match biopsy cores to target ROIs.
    NEEDLE_RADIUS = 2

    # ==========================================
    # 4. Model and labels
    # ==========================================
    IN_CHANNELS = 3
    NUM_CLASSES = 7

    # Compatibility values for the revised segmentation/MIL model.
    BASE_CHANNELS = 32
    MAX_ZONES = 20
    MIL_POOLING = "lme"
    LME_R = 8.0
    DROPOUT_RATE = 0.2
    # One canonical patient endpoint for every B/N experiment: normalized LME
    # pooling of lesion logits inside gland_mask, followed by sigmoid. AUPRC is
    # computed directly from this fixed continuous score; no contrast feature
    # or validation-fitted score calibration is used.
    SEG_PATIENT_POOLING = "logit_lme"
    SEG_REGION_POOLING = "top_percent"
    SEG_RISK_TOP_PERCENT = 1.0
    SEG_RISK_LME_R = 8.0
    SEG_PATIENT_CALIBRATION_C = 1.0
    SEG_PATIENT_CALIBRATION_MAX_ITER = 1000
    SEG_PATIENT_CALIBRATION_SEED = 42
    SEG_EVAL_COMPARE_PATIENT_POOLING = False
    # Validation/test patient scores are pooled strictly inside gland_mask, in
    # agreement with the patient-level training loss.
    SEG_EVAL_USE_GLAND_MASK = True

    # Label convention:
    # 0: negative/background, 1: benign, 2: ISUP1,
    # 3: ISUP2, ..., 6: ISUP5.
    CSPC_THRESHOLD = 3
    LESION_POSITIVE_THRESHOLD = CSPC_THRESHOLD
    INVALID_SYS_LABEL = -1
    PRED_PROB_THRESHOLD = 0.5
    TARGET_DICE_SWEEP_THRESHOLDS = tuple(round(x, 2) for x in np.arange(0.05, 1.00, 0.05))
    # Select one segmentation threshold on validation after checkpoint scoring.
    # Dense Dice inside valid gland masks is preferred; target csPCa Dice is the
    # automatic fallback when validation has no eligible dense/gland ground truth.
    VALIDATION_DICE_THRESHOLD_METRIC = "lesion_dice"
    TARGET_DICE_TOP_PERCENT = 1.0
    # Lesion FROC follows picai_eval 1.4.13 defaults: report-guided candidate
    # extraction, 26-connectivity, IoU >= 0.10, official split/merge handling,
    # and a curve over the candidates' continuous confidence scores.
    FROC_FP_PER_PATIENT_TARGETS = (0.5, 1.0, 2.0)
    PICAI_FROC_MIN_OVERLAP = 0.10
    PICAI_CANDIDATE_THRESHOLD = "dynamic-fast"
    PICAI_CANDIDATE_MIN_VOXELS = 10
    PICAI_CANDIDATE_MAX_LESIONS = 5
    PICAI_CANDIDATE_DYNAMIC_THRESHOLD_FACTOR = 2.5
    PICAI_CANDIDATE_REMOVE_ADJACENT = True
    # ROC classification operating points. These are sample-level FPR/specificity
    # values, not lesion-detection FP/patient; FROC uses the settings above.
    FIXED_SPECIFICITY_TARGET = 0.95
    FIXED_SENSITIVITY_TARGET = 0.90
    # Validation-frozen hard-decision protocol. Ranking metrics (AUPRC/AUROC)
    # remain threshold-free. The max-balanced-accuracy threshold is retained
    # separately in the frozen bundle as a secondary operating point.
    PATIENT_DECISION_THRESHOLD_RULE = "fixed_sensitivity"
    REGION_DECISION_THRESHOLD_RULE = "fixed_specificity"
    TBX_ROI_DECISION_THRESHOLD_RULE = "max_balanced_accuracy"
    # ROC operating thresholds are selected on validation and stored inside the
    # checkpoint. Final test only evaluates those frozen thresholds. AUROC,
    # AUPRC and the FROC sweep continue to consume continuous probabilities.
    VALIDATION_COMPUTE_OPERATING_METRICS = True
    VALIDATION_COMPUTE_FROC_METRICS = False
    FINAL_TEST_COMPUTE_OPERATING_METRICS = True
    FINAL_TEST_COMPUTE_FROC_METRICS = True
    # Final-test AUROC/AUPRC uncertainty uses a reproducible percentile
    # bootstrap. Patient-level observations are resampled by patient; region and
    # TBx voxel observations are cluster-resampled by patient to preserve their
    # within-patient correlation. CI is disabled during per-epoch validation to
    # avoid adding bootstrap cost to training.
    VALIDATION_COMPUTE_CONFIDENCE_INTERVALS = False
    FINAL_TEST_COMPUTE_CONFIDENCE_INTERVALS = True
    # CI is reported for the formal native/common best checkpoints. Top-K and
    # last checkpoints remain diagnostic and skip the expensive bootstrap.
    FINAL_TEST_CI_CHECKPOINT_LABELS = ("best", "best_native", "best_common")
    METRIC_CI_CONFIDENCE_LEVEL = 0.95
    METRIC_CI_BOOTSTRAP_SAMPLES = 1000
    METRIC_CI_SEED = 42
    # Track Bernoulli predictive entropy (0=certain, 1=maximally uncertain)
    # for voxel, supervised-subset, region, and patient predictions. Entropy is
    # diagnostic only and is never added to the optimisation objective.
    MONITOR_PREDICTION_ENTROPY = True
    # Dynamically retain the five epochs with the highest model-specific native
    # validation score. Fixed epoch snapshots are intentionally disabled.
    TOP_K_CHECKPOINTS = 5
    FINAL_TEST_INCLUDE_TOP_K = True
    FINAL_TEST_INCLUDE_BEST = True
    FINAL_TEST_INCLUDE_NATIVE_BEST = True
    FINAL_TEST_INCLUDE_COMMON_BEST = True
    FINAL_TEST_INCLUDE_LAST = True
    SAVE_DUAL_BEST_CHECKPOINTS = True

    # ==========================================
    # 5. Training hyperparameters
    # ==========================================
    DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
    SEED = 42

    NUM_EPOCHS = 150
    BATCH_SIZE = 4
    NUM_WORKERS = 2

    # Strict B/N supervision comparisons share one optimiser configuration.
    LR = 1e-4
    WEIGHT_DECAY = 1e-4
    LR_SCHEDULER = "CosineAnnealing"
    # Keep training for the full NUM_EPOCHS. Patience remains available as a
    # dormant compatibility value if early stopping is explicitly re-enabled.
    USE_EARLY_STOPPING = False
    EARLY_STOP_PATIENCE = 30
    GRAD_CLIP_NORM = 12.0

    # Strict B/N supervision comparisons share one TBx positive-class weight.
    POS_WEIGHT_VAL = 2.0
    SYS_POS_WEIGHT_VAL = 1.0
    SYS_FOCAL_ALPHA = 0.75
    SYS_FOCAL_GAMMA = 2.0
    USE_SYS_CLASS_BALANCED_BCE = True

    # ==========================================
    # 6. Loss / EM weighting configuration
    # ==========================================
    EM_LR_MULTIPLIER = 10.0

    USE_LOGVAR_CLAMP = True
    LOGVAR_MIN = -2.0
    LOGVAR_MAX = 2.0

    # The redesigned B/N runs named A0 did not optimise an outside-gland loss.
    # Gland restriction remains active for patient scoring and evaluation.
    USE_OUTSIDE_GLAND_PENALTY = False
    OUTSIDE_GLAND_LOSS_WEIGHT = 0.05 if USE_OUTSIDE_GLAND_PENALTY else 0.0
    OUTSIDE_GLAND_START_EPOCH = 1

    # Patient-level supervision derived from the same lesion risk map. No
    # independent classification head is added: patient logits are pooled from
    # voxel lesion logits.
    USE_PATIENT_RISK_LOSS = EXPERIMENT_MODE in {
        "B0_PATIENT_ONLY",
        "B4_TCIA_TBX_SBX_PATIENT",
        "N5_MIXED_PATIENT",
    }
    PATIENT_RISK_LOSS_WEIGHT = 0.05 if USE_PATIENT_RISK_LOSS else 0.0
    PATIENT_RISK_START_EPOCH = 1
    PATIENT_RISK_POOLING = "lme"
    PATIENT_RISK_LME_R = 8.0
    # Pool patient-level risk strictly inside a valid prostate gland mask.
    PATIENT_RISK_USE_GLAND_MASK = True
    # A dense RA lesion mask denotes radiological lesion presence, not
    # biopsy-confirmed patient csPCa. Keep the legacy fallback off so P has one
    # consistent clinical meaning across training and evaluation.
    USE_RA_LESION_PRESENCE_AS_PATIENT_LABEL = False

    FIXED_LOSS_WEIGHTS = {
        "grade_tbx": 0.0,
        "grade_sbx": 0.0,
        "lesion_dense": LESION_DENSE_LOSS_WEIGHT,
        "lesion_sparse": LESION_SPARSE_LOSS_WEIGHT,
        "lesion_sys": LESION_SYS_LOSS_WEIGHT,
        "lesion_outside_gland": OUTSIDE_GLAND_LOSS_WEIGHT,
        "lesion_patient": PATIENT_RISK_LOSS_WEIGHT,
        "gland": 0.0,
    }

    TBX_POSITIVE_SOFT_LABEL = 0.9
    TBX_NEGATIVE_SOFT_LABEL = 0.05
    # If False, TBx ROI loss is hard-label BCE on sampled target ROIs:
    #   positive: target_mask >= LESION_POSITIVE_THRESHOLD
    #   negative: 0 < target_mask < LESION_POSITIVE_THRESHOLD
    # target_mask == 0 remains unsampled/no-supervision.
    USE_TBX_POSITIVE_ONLY_LOSS = False
    # Optional Dice term for TBx supervision. It is evaluated only on sampled
    # ROI voxels and only for TBx-positive cases; BCE remains enabled.
    TBX_DICE_LOSS_WEIGHT = 0.0
    TBX_DICE_SMOOTH = 1e-5

    GRADE_TBX_START_EPOCH = 1
    GRADE_SBX_START_EPOCH = 1
    GLAND_START_EPOCH = 1

    LESION_W_SMALL = 5

    # ==========================================
    # 7. Ablation and augmentation
    # ==========================================
    USE_AUGMENTATION = True
    # Keep the original SBx zone masks even when a case also has TBx targets.
    MASK_TARGET_IN_SYS = False

    # ==========================================
    # 8. Visualization
    # ==========================================
    VIS_SUBDIR = "visualizations"
    SAVE_TRAIN_VIS = True
    TRAIN_VIS_EVERY_N_EPOCHS = 5
    TRAIN_VIS_MAX_PER_EPOCH = 4
    SAVE_VAL_VIS = True
    VAL_VIS_EVERY_N_EPOCHS = 5
    VAL_VIS_MAX_PER_TYPE = 2
    # Final-test artifacts are stored separately for every dataset/checkpoint.
    # "representative" keeps errors, representative source/label cases, and a
    # reserved set of good positive cases. A good case has Dice >= 0.80 for
    # dense/TBx supervision, perfect positive-region classification for SBx,
    # or a correctly detected positive patient. Use "good" to save only these
    # good cases, or "all", "errors", and "none" for the other policies.
    TEST_ARTIFACT_SUBDIR = "test_artifacts"
    TEST_VIS_POLICY = "representative"
    TEST_VIS_MAX_PER_RUN = 12
    TEST_VIS_LOW_DICE_THRESHOLD = 0.5
    TEST_VIS_GOOD_DICE_THRESHOLD = 0.8
    TEST_VIS_GOOD_MAX_PER_RUN = 4

    @classmethod
    def set_seed(cls):
        random.seed(cls.SEED)
        np.random.seed(cls.SEED)
        torch.manual_seed(cls.SEED)
        if torch.cuda.is_available():
            torch.cuda.manual_seed(cls.SEED)
            torch.cuda.manual_seed_all(cls.SEED)
            torch.backends.cudnn.deterministic = True
            torch.backends.cudnn.benchmark = False

    @classmethod
    def show(cls):
        print("-" * 50)
        print("Experiment Configurations:")
        for k, v in cls.__dict__.items():
            if not k.startswith("__") and not callable(v) and not isinstance(v, classmethod):
                print(f"{k:<32}: {v}")
        print("-" * 50)

    @classmethod
    def enabled_task_name(cls):
        enabled = []
        if getattr(cls, "USE_LESION_DENSE_TASK", False):
            enabled.append("LesDense")
        if getattr(cls, "USE_LESION_SPARSE_TASK", False):
            enabled.append("LesTBxROI")
        if getattr(cls, "USE_LESION_SYS_TASK", False):
            enabled.append("LesSysSBx")
        return "_".join(enabled) if enabled else "NoTask"

    @classmethod
    def get_experiment_name(cls):
        time_str = datetime.now().strftime("%Y%m%d_%H%M")
        weighting_name = "EM" if getattr(cls, "USE_EM_WEIGHTING", True) else "FixedW"
        task_name = cls.enabled_task_name()
        clamp_name = "Clamp" if getattr(cls, "USE_LOGVAR_CLAMP", False) else "NoClamp"
        curriculum_name = "Curr" if getattr(cls, "USE_CURRICULUM", False) else "NoCurr"
        em_lr = getattr(cls, "EM_LR_MULTIPLIER", 1.0)
        tag = getattr(cls, "EXPERIMENT_TAG", "")

        parts = [time_str]
        if tag:
            parts.append(str(tag))
        parts.extend([
            weighting_name,
            task_name,
            clamp_name,
            curriculum_name,
            f"EMlrX{em_lr:g}",
            f"LR{cls.LR}",
            str(cls.BEST_MODEL_METRIC),
        ])
        name = "_".join(parts)
        if not getattr(cls, "USE_AUGMENTATION", True):
            name += "_NoAug"
        return limit_experiment_name_component(name)
